### ISSUE TITLE
Should we always add demos?

### ISSUE THREAD

**Issue by manuel3108** [svelte-add/svelte-adders#11]
As we have seen in #10 and the bulma adder, we need to discuss if we want to ask the user if we should modify the `npm init svelte@next` template in order to show a small demos of the adders.

From my knowledge currently every adder is modifying the template to showcase how to use the added functionality without asking the user if he wants the demo to be added.

@babichjacob wrote this yesterday:
> I'm of the opinion that demos should always be included in just 1-2 files instead of asking the user for approval.  

I do not entirely agree with it. I think it's fine that we try to keep the demo in at least files possible, and try to modify the original template at least as possible.
But I personally don't agree that demo should be added every time.

* I see this adders as an easy way to setup new projects in a matter of seconds. So it might be a nice thing to get the demo the first one or two times I use this adder, but after those first time I think it's just adding useless overhead to delete those files after the adder has run. Imagine adding multiple adders on after the other to the template, and then needing to delete a bunch of files. It would personally kind distract and make me unhappy
* Preset also has the possibility to be run in an [non-interactive environment](https://usepreset.dev/docs/api/preset/#isinteractive). I could i.e. imagine this to be used a lot of adders at the same time, and you write all of them into i.e. a bash file, which then creates you a nice template. In such a case I would really not want to have those demos in there. 

Overall this just my opinion, so feel free to debate about it.

**Comment by babichjacob** [comment]
I see your point! I think we can update all the adders to use a flag to exclude demos that defaults to false.

There was [build tool logic added to `svelte-add/postcss`](https://github.com/svelte-add/postcss/blob/f2d4129b617d31cde3d71c7652500e83b90f5674/preset.ts#L31-L34) to accommodate old Snowpack SvelteKit projects but make Vite the primary one instead of throwing all that work away by allowing `--build-tool snowpack` to apply Snowpack-only preset logic (defaulting to Vite). We can use the same stuff in that file to have
```ts
const EXCLUDE_EXAMPLES = "excludeExamples";
Preset.option(EXCLUDE_EXAMPLES, false);
```

and anyone who doesn't want example / demo code they just end up deleting can add `--exclude-examples` to their `svelte-add` command. 

Documenting the option is another question. Since every adder should use the same convention (not being different with `--include-examples true` or `--no-demos` or whatever), it might be a good idea to inform people about that in the main `svelte-add/svelte-adders` repository. Either way, changing the command advertised in the specific adder's documentation to
```sh
npx svelte-add mdsvex # --exclude-examples
```
is a quick, self-explanatory way to show how to exclude examples.

Thoughts?

**Comment by manuel3108** [comment]
Yeah that would work for me for sure.

I still kinda don't understand your position against prompts, because it's just one or two key presses instead of ~15.
But either way, sounds like a good plan for me.

> Documenting the option is another question. Since every adder should use the same convention (not being different with --include-examples true or --no-demos or whatever), it might be a good idea to inform people about that in the main svelte-add/svelte-adders repository. Either way, changing the command advertised in the specific adder's documentation to

That's a great idea.
Nevertheless we should also document it in the specific repos, but I think that's what you were planning on.

**Comment by babichjacob** [comment]
Note to self: Document in `svelte-add/svelte-adders` because the PostCSS, Tailwind CSS, and shortly mdsvex adders all have this option now. Thank you for making this thread so we could do this!

**Comment by manuel3108** [comment]
Just wanted to update the bulma one, but I see you have already done it!

Do you also plan to add some doc about `--exclude-examples` to each repo? I think that might be another enhancement

**Comment by websocket98765** [comment]
Could this be the opposite? I.e. `--include-examples`. That way the command does a clean install, but users can add them if wanted.

**Comment by babichjacob** [comment]
> Could this be the opposite? I.e. `--include-examples`. That way the command does a clean install, but users can add them if wanted.

No, because I don't trust that people will know the adders are actually working if they don't have proof in front of them.

**Comment by websocket98765** [comment]
The ReadMe can guide users two ways: 1.) the command itself: `npx svelte-add tailwindcss --jit --include-examples`, 2.) And a sentence after it that says `Add class="text-green-600" to an element to see it working` which probably should exist in either case.

The current way doesn't actually _show_ them it's working because the site looks the same except for the "oh no...it changed my files!" moment, followed shortly by, "darn, now I need to check the repo to see what else it changed". :)

My view is I expect my tools to be "businessy"--to do what it says on the tin without adding junk to the project that needs to remove. I wouldn't want to install a slider component then have to search my code to see where it deposited the example or check if it overwrote a file. Only Svelte Kit gets the luxury of _knowing_ it's acting on a virgin project. IMO, others shouldn't alter the code beyond it's purpose for existing, unless explicitly indicated by the user.
