### ISSUE TITLE
Add svelte-preprocess

### ISSUE THREAD

**Issue by manuel3108** [svelte-add/svelte-adders#13]
We could add an adder for svelte-preprocess.

I know that we are currently duplicating the code at least in two places:
 * [postcss](https://github.com/svelte-add/postcss/blob/f2d4129b617d31cde3d71c7652500e83b90f5674/preset.ts#L85-L101)
 * [bulma](https://github.com/manuel3108/svelte-add-bulma/blob/9908e15d5f451f496755d2e5068cf0309fbce7ff/preset.ts#L19-L44)

I think we could easily extract that into its own adder, or into some shared code between those adders. 

I have also seen that we could directly link those presets into each other with [use-preset apply functionality](https://usepreset.dev/docs/actions/apply/#purpose). I think that might be also be an interesting part for the [tailwind adder](https://github.com/svelte-add/tailwindcss), where you are currently supposed to execute two command:
```shell
npx apply svelte-add/postcss # --no-ssh
npx apply svelte-add/tailwindcss # --no-ssh
```

**Comment by babichjacob** [comment]
> We could add an adder for svelte-preprocess.

Adding `svelte-preprocess` to a project without any options or installing other packages like `postcss` with it doesn't achieve anything.

> I know that we are currently duplicating the code at least in two places:
> 
>     * [postcss](https://github.com/svelte-add/postcss/blob/f2d4129b617d31cde3d71c7652500e83b90f5674/preset.ts#L85-L101)
> 
>     * [bulma](https://github.com/manuel3108/svelte-add-bulma/blob/9908e15d5f451f496755d2e5068cf0309fbce7ff/preset.ts#L19-L44)
> 
> 
> I think we could easily extract that into its own adder, or into some shared code between those adders.

Duplicated code is definitely a problem, but sharing code between adders isn't possible without circumventing the preset system—which we actually are able to do with the new custom `svelte-add` command (once it's fixed to work on Windows with `pnpx`).

> I have also seen that we could directly link those presets into each other with [use-preset apply functionality](https://usepreset.dev/docs/actions/apply/#purpose). I think that might be also be an interesting part for the [tailwind adder](https://github.com/svelte-add/tailwindcss), where you are currently supposed to execute two command:
> 
> ```shell
> npx apply svelte-add/postcss # --no-ssh
> npx apply svelte-add/tailwindcss # --no-ssh
> ```

This is kept as two separate commands because it's less difficult than checking / prompting during `svelte-add/tailwindcss` if `svelte-add/postcss` was already run. My goal is to minimize prompts—I'd even say the one asking if you want to update your packages should be removed and instructing people to run `(p)npm install` at the end of all their preset choices will be better.

**Comment by manuel3108** [comment]
> Adding svelte-preprocess to a project without any options or installing other packages like postcss with it doesn't achieve anything.

True, didn't thought about that.

>Duplicated code is definitely a problem, but sharing code between adders isn't possible without circumventing the preset system—which we actually are able to do with the new custom svelte-add command

Mhm, ok that might work. But I don't have a clue on how to do that thing.

> This is kept as two separate commands because it's less difficult than checking / prompting during svelte-add/tailwindcss if svelte-add/postcss was already run

I understand!

**Comment by Leftium** [comment]
Would it be possible to share code by exporting common methods from the svelte-adders package? Like this:

    // preset.ts

    import { adder } from "svelte-adders"

    adder.editSvelteConfig()
        .addPreprocessor('sveltePreprocess', {
            defaults: {
                style: "postcss",
            },
            postcss: true
        })

This example mirrors the [API for Preset's `editnodepackages()`](https://usepreset.dev/docs/actions/edit-json/#api-of-editnodepackages). One nice advantage: options can be passed as a true JS object instead of as a string.

Package `svelte-adders` could either wrap/extend package `apply` or work side-by-side. In the side-by-side case, editSvelteConfig() would be called inside `Preset.edit(["svelte.config.cjs"]).update((content)...`, inputting `content` and returning the new string.

I think it is possible to detect the context (imported as a module vs running as node script) so the common functionality could just be added to the existing `svelte-adders` package. If not, a new package could be created.
