### ISSUE TITLE
`pnpx svelte-add whatever` doesn't work on Windows

### ISSUE THREAD

**Issue by babichjacob** [svelte-add/svelte-adders#14]
`EISDIR: illegal operation on a directory, read`

**Comment by manuel3108** [comment]
Just FYI, seems completely broken on windows now

**Comment by manuel3108** [comment]
I think the problem lies way further down the road then this package, I will share my current thoughts below

I create and published [`svelte-add-test`](https://www.npmjs.com/package/svelte-add-test). This "package" essentially consists of two files: 
```json
// package.json
{
  "name": "svelte-add-test",
  "version": "0.0.1-alpha-4",
  "description": "",
  "main": "index.js",
  "bin": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {}
}
```

```js
// index.js
#! /usr/bin/env node
console.log("juhuu")
```
I have not uploaded to github or anything, because there really is not more.

Even with this, the error occurs. Currently looking into how to further debug pnpx

**Comment by babichjacob** [comment]
Thank you so much for your help investigating!!

**Comment by babichjacob** [comment]
Thank you so much for your help! This is now fixed permanently (hopefully).
